Test what exception is thrown out of finally
finally
